@extends('layouts.vertical', ['title' => 'My subscriptions'])

@section('content')
<div class="container-fluid platform-page">
    <div class="platform-heading"><div><span class="eyebrow">Department access</span><h4>My subscriptions</h4><p>Subscriptions you own, benefit from, or share through your department.</p></div><a href="{{ route('v1.requests.create',['type'=>'saas_subscription']) }}" class="btn btn-primary"><i class="mdi mdi-plus me-1"></i> Request SaaS</a></div>
    <div class="row g-3 mb-4"><div class="col-md-4"><div class="card platform-card"><div class="card-body p-3"><small class="text-muted text-uppercase">Active</small><h3>{{ $stats['active'] }}</h3></div></div></div><div class="col-md-4"><div class="card platform-card"><div class="card-body p-3"><small class="text-muted text-uppercase">Renewing in 30 days</small><h3>{{ $stats['renewal'] }}</h3></div></div></div><div class="col-md-4"><div class="card platform-card"><div class="card-body p-3"><small class="text-muted text-uppercase">Needs attention</small><h3>{{ $stats['attention'] }}</h3></div></div></div></div>
    <div class="card platform-card"><div class="card-header platform-card-header"><div><strong>Subscription access</strong><small>Account identifiers and payment instruments are always masked.</small></div></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Product</th><th>Owner</th><th>My access</th><th>Renewal</th><th>Monthly equivalent</th><th>Status</th></tr></thead><tbody>
        @forelse($subscriptions as $subscription)<tr><td><strong>{{ $subscription->vendor }} · {{ $subscription->product }}</strong><small class="d-block text-muted">{{ $subscription->plan ?: 'No plan' }} · {{ $subscription->masked_account }}</small></td><td>{{ $subscription->owner->name }}<small class="d-block text-muted">Renewal: {{ $subscription->renewalOwner->name }}</small></td><td>{{ $subscription->beneficiaries->contains(auth()->user())?'Named beneficiary':($subscription->owner_id===auth()->id()?'Owner':'Department access') }}<small class="d-block text-muted">{{ $subscription->department->name }}</small></td><td>{{ $subscription->next_renewal_date?->format('d M Y') ?? 'Not set' }}<small class="d-block text-muted">{{ $subscription->auto_renew?'Auto-renew governed':'Manual renewal' }}</small></td><td>IDR {{ number_format((float)$subscription->monthly_equivalent,0) }}</td><td><span class="badge bg-{{ $subscription->status==='active'?'success':(in_array($subscription->status,['payment_failed','suspended'])?'danger':'warning') }}-subtle text-{{ $subscription->status==='active'?'success':(in_array($subscription->status,['payment_failed','suspended'])?'danger':'warning') }}">{{ str($subscription->status)->replace('_',' ')->title() }}</span>@foreach($subscription->evidences->take(2) as $evidence)<a class="d-block small mt-1" href="{{ route('subscription-evidence.download',$evidence) }}">{{ str($evidence->type)->title() }} evidence</a>@endforeach</td></tr>
        @empty<tr><td colspan="6" class="text-center text-muted py-5"><i class="mdi mdi-credit-card-search-outline fs-32 d-block mb-2"></i>No subscriptions are assigned to you or your department.</td></tr>@endforelse
    </tbody></table></div></div>
</div>
@endsection
