@extends('layouts.vertical', ['title' => 'Request Operations'])

@section('content')
<div class="container-fluid platform-page">
    <div class="platform-heading"><div><span class="eyebrow">Operations</span><h4>Request queue</h4><p>Review demand, clear approvals, and keep deliveries moving.</p></div></div>
    <div class="row g-3 mb-4">@foreach([['submitted','Waiting review','clipboard-clock-outline'],['under_review','In review','clipboard-search-outline'],['in_progress','In delivery','progress-wrench'],['completed','Completed','check-decagram-outline']] as [$key,$label,$icon])<div class="col-6 col-lg-3"><div class="metric-card"><i class="mdi mdi-{{ $icon }}"></i><span>{{ $label }}</span><strong>{{ $stats[$key] ?? 0 }}</strong></div></div>@endforeach</div>
    <div class="card platform-card"><div class="card-header platform-card-header"><strong>All requests</strong><form method="GET" class="native-submit-form d-flex gap-2"><input name="q" class="form-control form-control-sm" value="{{ request('q') }}" placeholder="Search code or title"><select name="status" class="form-select form-select-sm"><option value="">All statuses</option>@foreach(\App\Enums\ServiceRequestStatus::cases() as $s)<option value="{{ $s->value }}" @selected(request('status')===$s->value)>{{ $s->label() }}</option>@endforeach</select><button class="btn btn-light btn-sm">Filter</button></form></div><div class="table-responsive"><table class="table platform-table mb-0"><thead><tr><th>Request</th><th>Requester</th><th>Service</th><th>Current stage</th><th>Status</th><th>Owner</th><th></th></tr></thead><tbody>@forelse($requests as $item)<tr><td><strong>{{ $item->title }}</strong><small>{{ $item->code }}</small></td><td>{{ $item->requester->name }}</td><td>{{ $item->type->label() }}</td><td>{{ $item->current_stage ?: 'Delivery' }}</td><td><span class="badge bg-{{ $item->status->color() }}-subtle text-{{ $item->status->color() }}">{{ $item->status->label() }}</span></td><td>{{ $item->assignee?->name ?: 'Unassigned' }}</td><td class="text-end"><a href="{{ route('admin.requests.show',$item) }}" class="btn btn-light btn-sm">Open</a></td></tr>@empty<tr><td colspan="7"><div class="empty-state">No requests match this filter.</div></td></tr>@endforelse</tbody></table></div>@if($requests->hasPages())<div class="card-footer">{{ $requests->links() }}</div>@endif</div>
</div>
@endsection
