@extends('layouts.vertical', ['title' => $serviceRequest->code])

@section('content')
<div class="container-fluid platform-page">
    <div class="platform-heading"><div><span class="eyebrow">{{ $serviceRequest->type->label() }} · {{ $serviceRequest->code }}</span><h4>{{ $serviceRequest->title }}</h4><p>Requested by {{ $serviceRequest->requester->name }} · {{ $serviceRequest->submitted_at?->format('d M Y, H:i') }}</p></div><div class="d-flex flex-wrap gap-2">@if($serviceRequest->approval_source === 'lark' && ($serviceRequest->approval_sync_status !== 'synced' || !$serviceRequest->approval_synced_at || $serviceRequest->approval_synced_at->lt(now()->subMinutes(30))))<span class="status-pill status-warning"><i class="mdi mdi-sync-alert me-1"></i>Approval data may be stale</span>@endif<span class="status-pill status-{{ $serviceRequest->status->color() }}">{{ $serviceRequest->status->label() }}</span></div></div>
    <div class="row g-4">
        <div class="col-xl-8">
            <div class="card platform-card mb-4"><div class="card-body p-4"><h6 class="section-title">Business context</h6><p>{{ $serviceRequest->description }}</p><div class="detail-grid">@foreach($serviceRequest->details as $key=>$value)<div><small>{{ str($key)->replace('_',' ')->title() }}</small><strong>{{ is_array($value) ? implode(', ', $value) : (is_bool($value) ? ($value ? 'Yes':'No') : ($value ?: '—')) }}</strong></div>@endforeach</div></div></div>
            @if($serviceRequest->aiCredential)<div class="card platform-card mb-4"><div class="card-body p-4"><span class="eyebrow">AI access</span><h6 class="mb-3">{{ $serviceRequest->aiCredential->key_alias }}</h6><div class="detail-grid"><div><small>Masked fingerprint</small><strong>{{ $serviceRequest->aiCredential->key_preview ?: 'Not returned by gateway' }}</strong></div><div><small>Status / expiry</small><strong>{{ str($serviceRequest->aiCredential->status)->title() }} · {{ $serviceRequest->aiCredential->expires_at?->format('d M Y') ?: 'No expiry' }}</strong></div><div><small>Allocation</small><strong>${{ number_format((float)$serviceRequest->aiCredential->max_budget,2) }} / {{ $serviceRequest->aiCredential->budget_duration }}</strong></div><div><small>Usage snapshot</small><strong>${{ number_format((float)$serviceRequest->aiCredential->current_spend,2) }} · synced {{ $serviceRequest->aiCredential->last_synced_at?->diffForHumans() ?: 'never' }}</strong></div></div></div></div>@endif
            @if($serviceRequest->subscription)<div class="card platform-card mb-4"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-start gap-3 mb-3"><div><span class="eyebrow">Subscription & financial impact</span><h6 class="mb-1">{{ $serviceRequest->subscription->vendor }} · {{ $serviceRequest->subscription->product }}</h6><p class="text-muted mb-0">{{ $serviceRequest->subscription->plan ?: 'No plan' }} · {{ $serviceRequest->subscription->masked_account }}</p></div><a href="{{ route('admin.subscriptions.index',['q'=>$serviceRequest->subscription->vendor]) }}" class="btn btn-light btn-sm">Open registry</a></div><div class="detail-grid"><div><small>Registry / renewal</small><strong>{{ str($serviceRequest->subscription->status)->replace('_',' ')->title() }} · {{ $serviceRequest->subscription->next_renewal_date?->format('d M Y') ?: 'Not scheduled' }}</strong></div><div><small>Approved value</small><strong>{{ $serviceRequest->subscription->currentVersion ? 'IDR '.number_format((float)$serviceRequest->subscription->currentVersion->normalized_idr,0) : 'Awaiting checker' }}</strong></div><div><small>Evidence</small><strong class="text-{{ $serviceRequest->subscription->evidences->isEmpty() ? 'warning' : 'success' }}">{{ $serviceRequest->subscription->evidences->isEmpty() ? 'Missing evidence' : $serviceRequest->subscription->evidences->count().' verified file(s)' }}</strong></div><div><small>Ledger records</small><strong>{{ $serviceRequest->financialEntries->count() }}</strong></div></div></div></div>@endif
            <div class="card platform-card"><div class="card-header platform-card-header"><div><strong>Complete audit trail</strong><small>Every business and delivery event on this request.</small></div></div><div class="card-body p-4"><div class="activity-stream">@foreach($serviceRequest->updates->sortByDesc('created_at') as $update)<div class="activity-item"><span class="activity-dot"></span><div><div class="d-flex justify-content-between"><strong>{{ $update->actor?->name ?? 'System' }}</strong><small>{{ $update->created_at->format('d M H:i') }}</small></div><p>{{ $update->message }}</p></div></div>@endforeach</div></div></div>
        </div>
        <div class="col-xl-4">
            @if($serviceRequest->approval_source !== 'lark' && in_array($serviceRequest->status, [\App\Enums\ServiceRequestStatus::Submitted,\App\Enums\ServiceRequestStatus::UnderReview], true) && auth()->user()->can('review service requests'))
                <div class="card platform-card mb-4"><div class="card-body p-4"><span class="eyebrow">Action required</span><h6>{{ $serviceRequest->current_stage }}</h6><form method="POST" action="{{ route('admin.requests.review',$serviceRequest) }}">@csrf<label class="form-label mt-3">Decision</label><select name="action" class="form-select" required><option value="approve">Approve this stage</option><option value="revision">Request revision</option><option value="reject">Reject request</option></select><label class="form-label mt-3">Review note</label><textarea name="note" rows="3" class="form-control" placeholder="Required for revision or rejection"></textarea><button class="btn btn-primary w-100 mt-3" type="submit">Record decision</button></form></div></div>
            @endif
            @if(in_array($serviceRequest->status, [\App\Enums\ServiceRequestStatus::Approved,\App\Enums\ServiceRequestStatus::InProgress,\App\Enums\ServiceRequestStatus::WaitingExternal], true) && auth()->user()->can('manage service requests'))
                <div class="card platform-card mb-4"><div class="card-body p-4"><h6 class="section-title">Delivery control</h6><form method="POST" action="{{ route('admin.requests.transition',$serviceRequest) }}">@csrf<label class="form-label">Next status</label><select name="status" class="form-select" required>@if($serviceRequest->status===\App\Enums\ServiceRequestStatus::Approved)<option value="in_progress">Start delivery</option>@else<option value="in_progress">Resume delivery</option><option value="waiting_external">Waiting on external party</option><option value="completed">Mark completed</option>@endif</select><label class="form-label mt-3">Owner</label><select name="assigned_to" class="form-select"><option value="">{{ $serviceRequest->assigned_to ? 'Keep current owner' : 'Select an owner' }}</option>@foreach($operators as $operator)<option value="{{ $operator->id }}" @selected($serviceRequest->assigned_to===$operator->id)>{{ $operator->name }}</option>@endforeach</select><label class="form-label mt-3">Update note</label><textarea name="note" class="form-control" rows="2"></textarea><button class="btn btn-primary w-100 mt-3">Update delivery</button></form></div></div>
                <div class="card platform-card mb-4"><div class="card-body p-4"><h6 class="section-title">Delivery details</h6><form method="POST" action="{{ route('admin.requests.delivery',$serviceRequest) }}">@csrf @method('PUT')<label class="form-label">Delivery status</label><select name="status" class="form-select">@foreach(['pending','active','delivered','expired'] as $value)<option value="{{ $value }}" @selected($serviceRequest->delivery?->status===$value)>{{ str($value)->title() }}</option>@endforeach</select><label class="form-label mt-3">Reference</label><input name="reference" class="form-control" value="{{ $serviceRequest->delivery?->reference }}"><label class="form-label mt-3">Access URL</label><input type="url" name="access_url" class="form-control" value="{{ $serviceRequest->delivery?->access_url }}"><div class="row g-2 mt-1"><div class="col-6"><label class="form-label">Starts</label><input type="date" name="starts_on" class="form-control" value="{{ $serviceRequest->delivery?->starts_on?->format('Y-m-d') }}"></div><div class="col-6"><label class="form-label">Ends</label><input type="date" name="ends_on" class="form-control" value="{{ $serviceRequest->delivery?->ends_on?->format('Y-m-d') }}"></div></div><button class="btn btn-light w-100 mt-3">Save details</button></form></div></div>
            @endif
            <div class="card platform-card mb-4"><div class="card-body p-4"><h6 class="section-title">End-to-end lifecycle</h6><div class="approval-steps"><div class="approval-step is-{{ $serviceRequest->approval_source === 'lark' && $serviceRequest->approval_sync_status !== 'synced' ? 'revision_requested' : 'approved' }}"><span><i class="mdi mdi-source-branch"></i></span><div><strong>Source · {{ str($serviceRequest->approval_source ?: $serviceRequest->source)->title() }}</strong><small>{{ $serviceRequest->lark_instance_code ? 'Lark '.$serviceRequest->lark_instance_code : 'Platform '.$serviceRequest->code }}{{ $serviceRequest->approval_synced_at ? ' · synced '.$serviceRequest->approval_synced_at->diffForHumans() : '' }}</small></div></div><div class="approval-step is-{{ $serviceRequest->approval_status->value === 'approved' ? 'approved' : 'pending' }}"><span><i class="mdi mdi-clipboard-check-outline"></i></span><div><strong>Approval decision</strong><small>{{ $serviceRequest->approval_status->label() }}</small></div></div><div class="approval-step is-{{ in_array($serviceRequest->fulfilment_status->value,['active','completed']) ? 'approved' : ($serviceRequest->fulfilment_status->value === 'failed' ? 'rejected' : 'pending') }}"><span><i class="mdi mdi-progress-wrench"></i></span><div><strong>Platform fulfilment</strong><small>{{ $serviceRequest->fulfilment_status->label() }}{{ $serviceRequest->delivery?->reference ? ' · '.$serviceRequest->delivery->reference : '' }}</small></div></div>@if($serviceRequest->subscription || $serviceRequest->financialEntries->isNotEmpty())<div class="approval-step is-approved"><span><i class="mdi mdi-cash-check"></i></span><div><strong>Financial accountability</strong><small>{{ $serviceRequest->subscription ? 'Subscription registry linked' : 'Ledger impact recorded' }}</small></div></div>@endif</div>@if($serviceRequest->lark_approval_url)<a href="{{ $serviceRequest->lark_approval_url }}" class="btn btn-light btn-sm w-100 mt-3" target="_blank" rel="noopener">Open authoritative approval in Lark</a>@endif</div></div>
            <div class="card platform-card mb-4"><div class="card-body p-4"><h6 class="section-title">Approval chain</h6><div class="approval-steps">@forelse($serviceRequest->approvals as $approval)<div class="approval-step is-{{ $approval->status }}"><span><i class="mdi {{ $approval->status==='approved'?'mdi-check':'mdi-clock-outline' }}"></i></span><div><strong>{{ $approval->stage }}</strong><small>Round {{ $approval->round }} · {{ str($approval->status)->replace('_',' ')->title() }}</small>@if($approval->note)<p>{{ $approval->note }}</p>@endif</div></div>@empty<div class="empty-state compact">Approval is managed by the authoritative source.</div>@endforelse</div></div></div>
            @if(($serviceRequest->type===\App\Enums\ServiceRequestType::AiToken || data_get($serviceRequest->details,'needs_ai_analyzer')) && !$serviceRequest->aiCredential && $serviceRequest->status===\App\Enums\ServiceRequestStatus::Approved)<form method="POST" action="{{ route('admin.requests.provision-ai',$serviceRequest) }}">@csrf<button class="btn btn-outline-primary w-100">Retry AI provisioning</button></form>@endif
            @if($serviceRequest->type===\App\Enums\ServiceRequestType::SaasSubscription && in_array($serviceRequest->status,[\App\Enums\ServiceRequestStatus::Approved,\App\Enums\ServiceRequestStatus::InProgress,\App\Enums\ServiceRequestStatus::WaitingExternal,\App\Enums\ServiceRequestStatus::Completed],true) && !$serviceRequest->subscription && auth()->user()->can('manage subscriptions'))<a href="{{ route('admin.subscriptions.index',['request'=>$serviceRequest->id]) }}" class="btn btn-outline-primary w-100 mt-3"><i class="mdi mdi-credit-card-plus-outline me-1"></i> Register approved subscription</a>@endif
        </div>
    </div>
</div>
@endsection
