@extends('layouts.vertical', ['title' => 'Applications'])

@section('content')
<div class="container-fluid platform-page">
    <div class="platform-heading">
        <div><span class="eyebrow">Delivery control plane</span><h4>Applications</h4><p>PostgreSQL catalog, non-blocking health checks, and GitHub–Lark task visibility in one workspace.</p></div>
        <div class="d-flex gap-2">@can('sync delivery tasks')<form method="POST" action="{{ route('admin.applications.sync') }}">@csrf<button class="btn btn-light btn-sm"><i class="mdi mdi-sync me-1"></i>Sync issues</button></form>@endcan @can('manage integrations')<button class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#application-modal"><i class="mdi mdi-plus me-1"></i>Add application</button>@endcan</div>
    </div>

    <div class="row g-3 mb-4">
        @foreach([['Applications',$stats['total'],'mdi-apps'],['Online',$stats['online'],'mdi-check-circle-outline'],['Open issues',$stats['open_tasks'],'mdi-source-branch'],['Sync failures',$stats['failed'],'mdi-alert-circle-outline']] as [$label,$value,$icon])
            <div class="col-6 col-xl-3"><div class="card platform-card h-100"><div class="card-body p-3 d-flex align-items-center justify-content-between"><div><small class="text-uppercase text-muted fw-semibold">{{ $label }}</small><h4 class="mb-0 mt-1">{{ $value }}</h4></div><span class="service-icon"><i class="mdi {{ $icon }}"></i></span></div></div></div>
        @endforeach
    </div>

    <div class="d-flex flex-wrap gap-2 mb-3">
        @foreach(['applications'=>'Applications','tasks'=>'Task sync','developers'=>'Developers','mappings'=>'Mappings'] as $tab=>$label)<a class="btn btn-sm {{ $activeTab===$tab?'btn-primary':'btn-light' }}" href="{{ route('admin.applications.index',['tab'=>$tab]) }}">{{ $label }}</a>@endforeach
    </div>

    @if($activeTab==='applications')
        <div class="card platform-card"><div class="card-header platform-card-header"><div><strong>Application catalog</strong><small>Health is refreshed in Horizon; loading this page never waits for domain probes.</small></div><form method="GET" class="native-submit-form d-flex flex-wrap gap-2"><input type="hidden" name="tab" value="applications"><input name="q" value="{{ request('q') }}" class="form-control form-control-sm" placeholder="Search name, repo, or domain"><select name="health" class="form-select form-select-sm"><option value="">Any health</option>@foreach(['online','degraded','offline','no_domain','unknown'] as $status)<option value="{{ $status }}" @selected(request('health')===$status)>{{ str($status)->replace('_',' ')->title() }}</option>@endforeach</select><select name="department_id" class="form-select form-select-sm"><option value="">All departments</option>@foreach($departments as $department)<option value="{{ $department->id }}" @selected((string)request('department_id')===(string)$department->id)>{{ $department->name }}</option>@endforeach</select><button class="btn btn-light btn-sm">Filter</button></form></div>
            <div class="table-responsive"><table class="table platform-table mb-0"><thead><tr><th>Application</th><th>Repository</th><th>Live domain</th><th>Health</th><th>Governance</th><th>Issues</th><th></th></tr></thead><tbody>
                @forelse($applications as $application)
                    @php($healthColor=match($application->health_status){'online'=>'success','degraded'=>'warning','offline'=>'danger',default=>'secondary'})
                    <tr><td><strong>{{ $application->display_name ?: $application->repo_full_name }}</strong><small>{{ $application->notes ? str($application->notes)->limit(55) : 'No operational note' }}</small></td><td><a href="https://github.com/{{ $application->repo_full_name }}" target="_blank" rel="noopener" class="font-monospace">{{ $application->repo_full_name }}</a></td><td>@if($application->domain)<a href="https://{{ $application->domain }}" target="_blank" rel="noopener">{{ $application->domain }}</a>@else<span class="text-muted">Internal / no domain</span>@endif</td><td><span class="badge bg-{{ $healthColor }}-subtle text-{{ $healthColor }}">{{ str($application->health_status)->replace('_',' ')->title() }}</span><small>{{ $application->response_time_ms ? $application->response_time_ms.' ms' : ($application->last_checked_at?->diffForHumans() ?? 'Queued') }}</small></td><td><strong>{{ $application->department?->name ?: 'Shared' }}</strong><small>{{ $application->cost_center ?: 'No cost center' }} · {{ $application->sync_enabled?'Sync on':'Sync off' }}</small></td><td>{{ $taskCounts[$application->repo_full_name] ?? 0 }}</td><td class="text-end">@can('manage integrations')<button type="button" class="btn btn-light btn-sm" data-edit-application data-repo="{{ $application->repo_full_name }}" data-name="{{ $application->display_name }}" data-domain="{{ $application->domain }}" data-department="{{ $application->department_id }}" data-cost-center="{{ $application->cost_center }}" data-sync="{{ (int)$application->sync_enabled }}" data-backup="{{ (int)$application->backup_enabled }}" data-notes="{{ $application->notes }}">Edit</button><form class="d-inline" method="POST" action="{{ route('admin.applications.destroy') }}" data-confirm="Remove this application from the catalog?">@csrf @method('DELETE')<input type="hidden" name="repo_full_name" value="{{ $application->repo_full_name }}"><button class="btn btn-link btn-sm text-danger">Remove</button></form>@endcan</td></tr>
                @empty<tr><td colspan="7"><div class="empty-state py-5"><i class="mdi mdi-apps"></i><strong>No applications found</strong><span>Add a repository without changing or redeploying code.</span></div></td></tr>@endforelse
            </tbody></table></div>@if($applications->hasPages())<div class="card-footer">{{ $applications->links() }}</div>@endif
        </div>
    @elseif($activeTab==='tasks')
        <div class="card platform-card"><div class="card-header platform-card-header"><div><strong>GitHub issue → Lark task</strong><small>GitHub remains the work source; mirrored mappings prove Lark delivery.</small></div><form method="GET" class="native-submit-form d-flex flex-wrap gap-2"><input type="hidden" name="tab" value="tasks"><input name="task_q" value="{{ request('task_q') }}" class="form-control form-control-sm" placeholder="Search issue or assignee"><select name="repository" class="form-select form-select-sm"><option value="">All repositories</option>@foreach($repositories as $repository)<option value="{{ $repository }}" @selected(request('repository')===$repository)>{{ $repository }}</option>@endforeach</select><select name="task_department_id" class="form-select form-select-sm"><option value="">All departments</option>@foreach($departments as $department)<option value="{{ $department->id }}" @selected((string) request('task_department_id')===(string) $department->id)>{{ $department->name }}</option>@endforeach</select><select name="sync_status" class="form-select form-select-sm"><option value="">Any sync</option>@foreach(['synced','pending','failed'] as $status)<option value="{{ $status }}" @selected(request('sync_status')===$status)>{{ str($status)->title() }}</option>@endforeach</select><button class="btn btn-light btn-sm">Filter</button></form></div>
            <div class="table-responsive"><table class="table platform-table mb-0"><thead><tr><th>Issue</th><th>Repository / department</th><th>Owner</th><th>Effort</th><th>GitHub</th><th>Lark</th><th>Sync</th></tr></thead><tbody>@forelse($tasks as $task)@php($syncStatus=$task->mapping?'synced':($task->sync_status==='failed'?'failed':'pending'))<tr><td><strong>#{{ $task->issue_number }} {{ $task->title }}</strong><small>{{ str($task->state)->title() }} · updated {{ $task->remote_updated_at?->diffForHumans() ?: 'unknown' }}</small></td><td>{{ $task->repository }}<small>{{ $task->department?->name ?: 'Unassigned department' }}</small></td><td>{{ $task->assignee ?: 'Unassigned' }}</td><td>{{ $task->mandays !== null ? rtrim(rtrim($task->mandays,'0'),'.').' md' : '—' }}</td><td><a href="{{ $task->github_url }}" target="_blank" rel="noopener">Open issue</a></td><td>@if($task->lark_task_url)<a href="{{ $task->lark_task_url }}" target="_blank" rel="noopener">Open task</a>@elseif($task->mapping?->taskUrl())<a href="{{ $task->mapping->taskUrl() }}" target="_blank" rel="noopener">Open task</a>@elseif($task->mapping)<span class="font-monospace" title="Set LARK_TASK_URL_TEMPLATE with a {guid} placeholder to enable deep links">{{ str($task->mapping->lark_task_guid)->limit(14) }}</span>@else—@endif</td><td><span class="badge bg-{{ $syncStatus==='synced'?'success':($syncStatus==='failed'?'danger':'warning') }}-subtle text-{{ $syncStatus==='synced'?'success':($syncStatus==='failed'?'danger':'warning') }}">{{ str($syncStatus)->title() }}</span>@if($task->sync_error)<small class="text-danger">{{ str($task->sync_error)->limit(80) }}</small>@endif</td></tr>@empty<tr><td colspan="7"><div class="empty-state py-5">No GitHub issues match this filter.</div></td></tr>@endforelse</tbody></table></div>@if($tasks->hasPages())<div class="card-footer">{{ $tasks->links() }}</div>@endif
        </div>
    @elseif($activeTab==='developers')
        <div class="card platform-card"><div class="card-header platform-card-header"><div><strong>Developer identities</strong><small>Read-only mirror owned by github-lark-sync.</small></div></div><div class="table-responsive"><table class="table platform-table mb-0"><thead><tr><th>GitHub</th><th>Lark identity</th><th>Email</th><th>Section</th><th>Updated</th></tr></thead><tbody>@forelse($developers as $developer)<tr><td><strong>@@{{ $developer->github_username }}</strong><small>{{ $developer->github_user_id ?: 'No GitHub user ID' }}</small></td><td>{{ $developer->lark_name ?: 'Unmapped' }}<small>{{ $developer->lark_open_id }}</small></td><td>{{ $developer->lark_email ?: '—' }}</td><td>{{ $developer->lark_section_guid ?: '—' }}</td><td>{{ $developer->updated_at?->diffForHumans() }}</td></tr>@empty<tr><td colspan="5"><div class="empty-state py-5">No developer mappings mirrored yet.</div></td></tr>@endforelse</tbody></table></div>@if($developers->hasPages())<div class="card-footer">{{ $developers->links() }}</div>@endif</div>
    @else
        <div class="card platform-card"><div class="card-header platform-card-header"><div><strong>Production mapping mirror</strong><small>Rows written by github-lark-sync into platform PostgreSQL.</small></div></div><div class="table-responsive"><table class="table platform-table mb-0"><thead><tr><th>GitHub issue</th><th>Repository</th><th>Lark task GUID</th><th>Lark user</th><th>Updated</th></tr></thead><tbody>@forelse($mappings as $mapping)<tr><td><a href="{{ $mapping->github_issue_url }}" target="_blank" rel="noopener">#{{ $mapping->github_issue_number ?: '—' }}</a></td><td>{{ $mapping->repo_full_name ?: 'Unknown' }}</td><td class="font-monospace">{{ $mapping->lark_task_guid }}</td><td class="font-monospace">{{ $mapping->lark_user_id ?: '—' }}</td><td>{{ $mapping->updated_at?->diffForHumans() }}</td></tr>@empty<tr><td colspan="5"><div class="empty-state py-5">No mirrored mappings yet.</div></td></tr>@endforelse</tbody></table></div>@if($mappings->hasPages())<div class="card-footer">{{ $mappings->links() }}</div>@endif</div>
    @endif
</div>

@can('manage integrations')
<div class="modal fade" id="application-modal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><form method="POST" action="{{ route('admin.applications.upsert') }}" id="application-form">@csrf<input type="hidden" name="original_repo"><div class="modal-header"><div><h5 class="modal-title">Application catalog entry</h5><small class="text-muted">PostgreSQL is the source of truth.</small></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label">GitHub repository</label><input name="repo_full_name" class="form-control" required placeholder="owner/repository"></div><div class="col-md-6"><label class="form-label">Application name</label><input name="display_name" class="form-control" required></div><div class="col-md-6"><label class="form-label">Live domain</label><input name="domain" class="form-control" placeholder="app.virtuenet.space"><div class="form-text">Hostname only; HTTPS is used for health probes.</div></div><div class="col-md-3"><label class="form-label">Department</label><select name="department_id" class="form-select"><option value="">Shared</option>@foreach($departments as $department)<option value="{{ $department->id }}">{{ $department->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Cost center</label><input name="cost_center" class="form-control" maxlength="100"></div><div class="col-12"><label class="form-label">Operational notes</label><textarea name="notes" class="form-control" rows="3" maxlength="5000"></textarea></div><div class="col-md-6"><div class="form-check form-switch"><input type="hidden" name="sync_enabled" value="0"><input class="form-check-input" type="checkbox" name="sync_enabled" id="application-sync" value="1" checked><label class="form-check-label" for="application-sync">Sync GitHub issues to Lark</label></div></div><div class="col-md-6"><div class="form-check form-switch"><input type="hidden" name="backup_enabled" value="0"><input class="form-check-input" type="checkbox" name="backup_enabled" id="application-backup" value="1" checked><label class="form-check-label" for="application-backup">Include in backup policy</label></div></div></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary">Save application</button></div></form></div></div></div>
@endcan
@endsection

@section('script-bottom')
<script>
document.addEventListener('DOMContentLoaded', () => {
    const modal = document.getElementById('application-modal');
    const form = document.getElementById('application-form');
    if (!modal || !form) return;
    modal.addEventListener('hidden.bs.modal', () => { form.reset(); form.elements.original_repo.value = ''; });
    document.querySelectorAll('[data-edit-application]').forEach(button => button.addEventListener('click', () => {
        form.elements.original_repo.value = button.dataset.repo || '';
        form.elements.repo_full_name.value = button.dataset.repo || '';
        form.elements.display_name.value = button.dataset.name || '';
        form.elements.domain.value = button.dataset.domain || '';
        form.elements.department_id.value = button.dataset.department || '';
        form.elements.cost_center.value = button.dataset.costCenter || '';
        form.elements.notes.value = button.dataset.notes || '';
        document.getElementById('application-sync').checked = button.dataset.sync === '1';
        document.getElementById('application-backup').checked = button.dataset.backup === '1';
        bootstrap.Modal.getOrCreateInstance(modal).show();
    }));
});
</script>
@endsection
